// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("SqFt")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Pool, Sauna, Wi-Fi",
                            CreatedDate = new DateTime(2023, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Details = "A luxury villa with a stunning ocean view and private beach access.",
                            ImgUrl = "https://example.com/images/villa1.jpg",
                            Name = "Ocean Breeze Villa",
                            Occupancy = 6,
                            Rate = 350.0,
                            SqFt = 2200,
                            UpdatedDate = new DateTime(2024, 4, 20, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Fireplace, Hot Tub, Hiking Trails",
                            CreatedDate = new DateTime(2022, 11, 12, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            Details = "Cozy villa nestled in the mountains, perfect for a winter getaway.",
                            ImgUrl = "https://example.com/images/villa2.jpg",
                            Name = "Mountain Escape",
                            Occupancy = 4,
                            Rate = 270.0,
                            SqFt = 1800,
                            UpdatedDate = new DateTime(2024, 3, 30, 9, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Wi-Fi, Rooftop Access, City View",
                            CreatedDate = new DateTime(2023, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "A stylish villa in the heart of the city, close to all attractions.",
                            ImgUrl = "https://example.com/images/villa3.jpg",
                            Name = "Urban Luxe",
                            Occupancy = 3,
                            Rate = 300.0,
                            SqFt = 1500,
                            UpdatedDate = new DateTime(2024, 1, 25, 13, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Boat Dock, BBQ Grill, Deck",
                            CreatedDate = new DateTime(2023, 8, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Serene villa by the lake, ideal for peaceful weekends.",
                            ImgUrl = "https://example.com/images/villa4.jpg",
                            Name = "Lakeside Retreat",
                            Occupancy = 4,
                            Rate = 200.0,
                            SqFt = 1600,
                            UpdatedDate = new DateTime(2024, 2, 18, 10, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Pool, Outdoor Shower, Wi-Fi",
                            CreatedDate = new DateTime(2022, 9, 22, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            Details = "Modern villa with stunning desert views and luxurious interiors.",
                            ImgUrl = "https://example.com/images/villa5.jpg",
                            Name = "Desert Dream",
                            Occupancy = 5,
                            Rate = 280.0,
                            SqFt = 1900,
                            UpdatedDate = new DateTime(2024, 4, 1, 12, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "Garden, Fireplace, Bicycles",
                            CreatedDate = new DateTime(2023, 3, 3, 15, 40, 0, 0, DateTimeKind.Unspecified),
                            Details = "Rustic villa surrounded by nature and rolling hills.",
                            ImgUrl = "https://example.com/images/villa6.jpg",
                            Name = "Countryside Charm",
                            Occupancy = 4,
                            Rate = 180.0,
                            SqFt = 1700,
                            UpdatedDate = new DateTime(2024, 4, 12, 16, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Amenity = "Hammocks, Wi-Fi, Guided Tours",
                            CreatedDate = new DateTime(2022, 6, 17, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Hidden villa deep in the jungle, surrounded by wildlife.",
                            ImgUrl = "https://example.com/images/villa7.jpg",
                            Name = "Jungle Hideaway",
                            Occupancy = 5,
                            Rate = 320.0,
                            SqFt = 2000,
                            UpdatedDate = new DateTime(2024, 1, 10, 11, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Amenity = "Private Beach, Pool, Butler Service",
                            CreatedDate = new DateTime(2023, 4, 5, 7, 10, 0, 0, DateTimeKind.Unspecified),
                            Details = "Secluded villa on a private island, ultimate luxury experience.",
                            ImgUrl = "https://example.com/images/villa8.jpg",
                            Name = "Island Paradise",
                            Occupancy = 6,
                            Rate = 500.0,
                            SqFt = 2500,
                            UpdatedDate = new DateTime(2024, 4, 15, 8, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Amenity = "Heated Floors, Sauna, Ski Storage",
                            CreatedDate = new DateTime(2022, 12, 1, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            Details = "Luxury villa near ski slopes, ideal for winter sports lovers.",
                            ImgUrl = "https://example.com/images/villa9.jpg",
                            Name = "Ski Chalet",
                            Occupancy = 5,
                            Rate = 400.0,
                            SqFt = 2100,
                            UpdatedDate = new DateTime(2024, 2, 5, 9, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Amenity = "Outdoor Bar, Pool, Wi-Fi",
                            CreatedDate = new DateTime(2023, 7, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Vibrant and colorful villa in a tropical setting with lush gardens.",
                            ImgUrl = "https://example.com/images/villa10.jpg",
                            Name = "Tropical Bliss",
                            Occupancy = 5,
                            Rate = 330.0,
                            SqFt = 1950,
                            UpdatedDate = new DateTime(2024, 4, 18, 17, 35, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
